### ISSUE TITLE
Broken ore dictionary registration - NOT Game-breaking

### ISSUE THREAD

**Issue by syndicate25** [Roadhog360/Et-Futurum-Requiem#187]
### Please check any boxes that apply to you and your issue

- [ ] I use a translator application to post this issue.

- [ ] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

- [x] This is a code problem. Please link the probably problematic lines of code in the issue and/or explain in detail what is wrong.

### Version number of Et-Futurum-Requiem (IMPORTANT)
> _Specify the actual version, please don't just say "latest", tell us the version number of the mod in-game, or the name the jar had when downloading it._
Et_Futurum_Requiem-2.4.0

### Describe the issue (IMPORTANT)
> _A list of steps to reproduce the issue may be helpful too. Screenshots could also prove beneficial for visual issues._
Launching the game with the Progressive Survival Modpack.  **THIS IS NOT A CRASH.**  I doubt it's that impactful to the game, but I wanted to report this in case you wanted to fix it.  Looks like just a couple broken oredict registrations.

[01:31:08] [Client thread/WARN] [FML]: ****************************************
[01:31:08] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorWood has occurred. It adds an item (type: class net.malisis.doors.door.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod §5§oEt Futurum Requiem report it to them!
[01:31:08] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(Unknown Source)
[01:31:08] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(Unknown Source)
[01:31:08] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.recipes.ModRecipes.registerOreDictionary(ModRecipes.java:94)
[01:31:08] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.recipes.ModRecipes.init(ModRecipes.java:58)
[01:31:08] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.EtFuturum.init(EtFuturum.java:408)
[01:31:08] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[01:31:08] [Client thread/WARN] [FML]: ****************************************
[01:31:08] [Client thread/WARN] [FML]: ****************************************
[01:31:08] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorIron has occurred. It adds an item (type: class net.malisis.doors.door.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod §5§oEt Futurum Requiem report it to them!
[01:31:08] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(Unknown Source)
[01:31:08] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(Unknown Source)
[01:31:08] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.recipes.ModRecipes.registerOreDictionary(ModRecipes.java:100)
[01:31:08] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.recipes.ModRecipes.init(ModRecipes.java:58)
[01:31:08] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.EtFuturum.init(EtFuturum.java:408)
[01:31:08] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[01:31:08] [Client thread/WARN] [FML]: ****************************************

### Mod list (OPTIONAL)
> _Crash reports contain the mod list to copy. Please use Pastebin or Gist if it is too large. If you don't have a crash report, open any world and hold F3 + C for 10 seconds to crash the game manually._

Mod list, if you want it:

https://pastebin.com/uPbjEi3P

### Additional Context (OPTIONAL)
> _Any other info that may have been missed? If you suspect other mods to cause this issue, list them here and tell us why you suspect each of them._

Nothing additional to add here.  I suspect this is a simple thing to resolve anyway.  Let me know if you need any more information.

**Comment by GregoriusT** [comment]
@Roadhog360 dumb question, Malisis doors, is that a Mod you have Compat with or a Mod that has Compat with you and replaced the Door Entry?

And yes whoever is responsible for this, this is VERY MUCH a bug with whoever registers that Door Item. I just dont exactly know "who" does it.

**Comment by Roadhog360** [comment]
No, I don't add anything for that mod, some other mod is doing it. I have never even heard of that mod

**Comment by GregoriusT** [comment]
Okay I have doublechecked your Code, apparently you are indeed doing everything right. That Doors Mod is replacing vanilla Items without properly overriding their Item registration, so nothing you did wrong there.

**Comment by GregoriusT** [comment]
You might be able to hack-register the Door Item for them, but that might be difficult.

And NORMALLY Mods do not replace Items of other Mods or Items of Vanilla, so this particular mistake being blamed on you is like a 1% error, heck I made that mistake like 3 times at least, until I got pissed at it and made my OreDict register utility Function crash the Game should I make that mistake myself AGAIN... People made this mistake a LOT, so I do understand why the wording is so annoyed at people repeating it over and over. But the real solution would have been to crash the Game whenever an unregistered Item goes to the OreDictionary, because nobody reads these frikkin FML Logs... At least then the Issue would have been fixed ages ago by the actual Mod Dev instead of being blamed on others a decade later...

**Comment by syndicate25** [comment]
Certainly didn't intend to cause a problem here, but thanks for responding so quickly.

Out of curiosity (if you don't mind sharing) what is the consequence of what this mod is not doing, that it should be doing? Should I consider removing it to prevent issues? I don't think Malisis Doors is being developed any longer.  I understand that it is not your creation or your problem though, so I don't expect any help in that area. 

Thanks again!

**Comment by GregoriusT** [comment]
That depends on if any Mod uses the "doorWood" and "doorIron" OreDictionary Entries for their Recipes, otherwise everything should be fine.
