### ISSUE TITLE
server crash - generator problem? (2.4.0)

### ISSUE THREAD

**Issue by Cronosus** [Roadhog360/Et-Futurum-Requiem#244]
- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

### Version number of Et-Futurum-Requiem (IMPORTANT)
2.4.0

### Describe the issue (IMPORTANT)
when one of my players join server, i got eror, and after repeated tries to join server crashes
its caused when hes in Aroma dimension, and probably unsuccesfull generation of Mesa near him

### Mod list (OPTIONAL)
[crash-2023-02-22_18.53.17-server.txt](https://github.com/Roadhog360/Et-Futurum-Requiem/files/10807540/crash-2023-02-22_18.53.17-server.txt)

### Additional Context (OPTIONAL)
error in log when player tries to join

```
19:05:59] [Server thread/WARN]: Failed to handle packet for IP
net.minecraft.util.ReportedException: Exception getting block type in world
	at net.minecraft.world.World.func_147439_a(World.java:711) ~[ahb.class:?]
	at net.minecraft.world.World.func_72849_a(World.java:1221) ~[ahb.class:?]
	at net.minecraft.world.World.func_72957_l(World.java:1214) ~[ahb.class:?]
	at ganymedes01.etfuturum.world.structure.StructureMesaMineshaftPieces$Piece.skyLight(StructureMesaMineshaftPieces.java:880) ~[StructureMesaMineshaftPieces$Piece.class:?]
	at ganymedes01.etfuturum.world.structure.StructureMesaMineshaftPieces$MesaCorridor.func_74875_a(StructureMesaMineshaftPieces.java:387) ~[StructureMesaMineshaftPieces$MesaCorridor.class:?]
	at net.minecraft.world.gen.structure.StructureStart.func_75068_a(StructureStart.java:45) ~[avm.class:?]
	at net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:93) ~[ave.class:?]
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:386) ~[aqz.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1206) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217) ~[ms.class:?]
	at net.minecraft.server.management.PlayerManager$PlayerInstance.<init>(PlayerManager.java:408) ~[mr.class:?]
	at net.minecraft.server.management.PlayerManager.func_72690_a(PlayerManager.java:121) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72691_b(PlayerManager.java:212) ~[mq.class:?]
	at net.minecraft.server.management.PlayerManager.func_72685_d(PlayerManager.java:305) ~[mq.class:?]
	at net.minecraft.server.management.ServerConfigurationManager.func_72358_d(ServerConfigurationManager.java:421) ~[oi.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147347_a(NetHandlerPlayServer.java:593) ~[nh.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer.func_148833_a(C03PacketPlayer.java:36) ~[jd.class:?]
	at net.minecraft.network.play.client.C03PacketPlayer$C04PacketPlayerPosition.func_148833_a(C03PacketPlayer.java:144) ~[je.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245) ~[ej.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181) [nc.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:432) [lt.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:841) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:693) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.util.ConcurrentModificationException
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1445) ~[?:1.8.0_275]
	at java.util.HashMap$ValueIterator.next(HashMap.java:1474) ~[?:1.8.0_275]
	at net.minecraft.world.gen.structure.MapGenStructure.func_75051_a(MapGenStructure.java:89) ~[ave.class:?]
	at net.minecraft.world.gen.ChunkProviderGenerate.func_73153_a(ChunkProviderGenerate.java:386) ~[aqz.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73153_a(ChunkProviderServer.java:442) ~[ms.class:?]
	at net.minecraft.world.chunk.Chunk.func_76624_a(Chunk.java:1206) ~[apx.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.originalLoadChunk(ChunkProviderServer.java:311) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:217) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73158_c(ChunkProviderServer.java:185) ~[ms.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_73154_d(ChunkProviderServer.java:323) ~[ms.class:?]
	at net.minecraft.world.World.func_72964_e(World.java:799) ~[ahb.class:?]
	at net.minecraft.world.World.func_147439_a(World.java:702) ~[ahb.class:?]
	... 26 more
```

**Comment by GregoriusT** [comment]
Step 1: Try to update Et Futurum Requiem on the Server , maybe this Bug has been fixed already.

Step 2: If that failed, please provide a Mod List because this sort of Issue is really hard to debug.

**Comment by Roadhog360** [comment]
Mesa mineshaft skylight checks are fixed after this version. Please verify your game version before creating issues. If this somehow still occurs on 2.4.3 we can reopen this.
