### ISSUE TITLE
Bees cause crash

### ISSUE THREAD

**Issue by OrcHunter97** [Roadhog360/Et-Futurum-Requiem#337]
### Please check any boxes that apply to you and your issue

- [x] I use a translator application to post this issue.

- [x] This is a crash. Please upload, Pastebin, Gist or copypaste the whole crash report along with this issue.

- [ ] This is a mod incompatibility. If I do this in vanilla Forge with only Et Futurum Requiem installed, it works normally.

### Version number of Et-Futurum-Requiem (IMPORTANT)

2.5.0

### Describe the issue (IMPORTANT)

I keep bees in an underground room. Crash occurs periodically.

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 24.09.23 14:35
Description: Ticking entity

java.lang.NullPointerException: Ticking entity
	at ganymedes01.etfuturum.entities.ai.FlyingPathFinder.isSafe(FlyingPathFinder.java:157)
	at ganymedes01.etfuturum.entities.ai.FlyingPathFinder.func_75860_b(FlyingPathFinder.java:139)
	at net.minecraft.pathfinding.PathFinder.func_75861_a(SourceFile:89)
	at net.minecraft.pathfinding.PathFinder.func_75857_a(SourceFile:60)
	at ganymedes01.etfuturum.entities.ai.ExtendedPathNavigator.getEntityPathToXYZ(ExtendedPathNavigator.java:71)
	at ganymedes01.etfuturum.entities.ai.ExtendedPathNavigator.getPathEntityToEntity(ExtendedPathNavigator.java:81)
	at ganymedes01.etfuturum.entities.ai.ExtendedPathNavigator.func_75494_a(ExtendedPathNavigator.java:55)
	at ganymedes01.etfuturum.entities.ai.ExtendedPathNavigator.func_75497_a(ExtendedPathNavigator.java:46)
	at net.minecraft.entity.ai.EntityAIFollowParent.func_75246_d(SourceFile:62)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:640)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:452)
	at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
	at ganymedes01.etfuturum.entities.EntityBee.func_70636_d(EntityBee.java:392)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:272)
	at ganymedes01.etfuturum.entities.EntityBee.func_70071_h_(EntityBee.java:562)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at ganymedes01.etfuturum.entities.ai.FlyingPathFinder.isSafe(FlyingPathFinder.java:157)
	at ganymedes01.etfuturum.entities.ai.FlyingPathFinder.func_75860_b(FlyingPathFinder.java:139)
	at net.minecraft.pathfinding.PathFinder.func_75861_a(SourceFile:89)
	at net.minecraft.pathfinding.PathFinder.func_75857_a(SourceFile:60)
	at ganymedes01.etfuturum.entities.ai.ExtendedPathNavigator.getEntityPathToXYZ(ExtendedPathNavigator.java:71)
	at ganymedes01.etfuturum.entities.ai.ExtendedPathNavigator.getPathEntityToEntity(ExtendedPathNavigator.java:81)
	at ganymedes01.etfuturum.entities.ai.ExtendedPathNavigator.func_75494_a(ExtendedPathNavigator.java:55)
	at ganymedes01.etfuturum.entities.ai.ExtendedPathNavigator.func_75497_a(ExtendedPathNavigator.java:46)
	at net.minecraft.entity.ai.EntityAIFollowParent.func_75246_d(SourceFile:62)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:103)
	at net.minecraft.entity.EntityLiving.func_70619_bc(EntityLiving.java:640)
	at net.minecraft.entity.EntityLivingBase.func_70636_d(EntityLivingBase.java:1774)
	at net.minecraft.entity.EntityLiving.func_70636_d(EntityLiving.java:452)
	at net.minecraft.entity.EntityAgeable.func_70636_d(SourceFile:95)
	at net.minecraft.entity.passive.EntityAnimal.func_70636_d(SourceFile:37)
	at ganymedes01.etfuturum.entities.EntityBee.func_70636_d(EntityBee.java:392)
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:1611)
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:272)
	at ganymedes01.etfuturum.entities.EntityBee.func_70071_h_(EntityBee.java:562)
	at net.minecraft.world.World.func_72866_a(World.java:2070)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:648)
	at net.minecraft.world.World.func_72870_g(World.java:2034)
	at WorldServerOF.func_72870_g(WorldServerOF.java:347)

-- Entity being ticked --
Details:
	Entity Type: etfuturum.bee (ganymedes01.etfuturum.entities.EntityBee)
	Entity ID: 747
	Entity Name: Пчела
	Entity's Exact location: 616,51, 96,65, 1210,53
	Entity's Block location: World: (616,96,1210), Chunk: (at 8,6,10 in 38,75; contains blocks 608,0,1200 to 623,255,1215), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
	Entity's Momentum: -0,01, 0,00, -0,02
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1887)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:489)

-- Affected level --
Details:
	Level name: ДэдВуд
	All players: 1 total; [EntityPlayerMP['Lotar II'/1187, l='ДэдВуд', x=618,00, y=93,00, z=1214,20]]
	Chunk stats: ServerChunkCache: 904 Drop: 0
	Level seed: -1707624051288806824
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (470,64,1085), Chunk: (at 6,4,13 in 29,67; contains blocks 464,0,1072 to 479,255,1087), Region: (0,2; contains chunks 0,64 to 31,95, blocks 0,0,1024 to 511,255,1535)
	Level time: 24943214 game time, 28508459 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 12909 (now: true), thunder time: 145669 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:636)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:186)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 12935857848 bytes (12336 MB) / 13757317120 bytes (13120 MB) up to 15636365312 bytes (14912 MB)
	JVM Flags: 8 total; -Xmn128M -Xmx14909M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 44, tcache: 0, allocated: 13, tallocated: 96
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 Optifine OptiFine_1.7.10_HD_U_E7 38 mods loaded, 38 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar) 
	UCHIJAAAA	ItemBlacklist{1.2.0.8} [ItemBlacklist] (ItemBlacklist-1.7.10-1.2.0.8.jar) 
	UCHIJAAAA	aether_legacy{v1.1.2.2} [The Aether] (aether-1.7.10-v1.1.2.2.jar) 
	UCHIJAAAA	BetterFoliage{2.0.17} [Better Foliage] (BetterFoliage-MC1.7.10-2.0.17.jar) 
	UCHIJAAAA	bettervanilla{1.1.1} [BetterVanilla] (BetterVanilla-1.7.10-1.1.1.jar) 
	UCHIJAAAA	BiblioCraft{1.11.7} [BiblioCraft] (BiblioCraft[v1.11.7][MC1.7.10].jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJAAAA	campfirebackport{1.7.10-1.10} [Campfire Backport] (campfirebackport-1.7.10-1.10.jar) 
	UCHIJAAAA	cartload{1.0.2} [CartLoad] (cartload-mc1.7.10-1.0.2.jar) 
	UCHIJAAAA	craftguide{1.7.1.0} [CraftGuide] (CraftGuide-1.7.1.0-forge.jar) 
	UCHIJAAAA	DamageIndicatorsMod{3.3.2} [Damage Indicators] (Damage-Indicators-Mod-1.7.10.jar) 
	UCHIJAAAA	deathwatch{1.1} [Deathwatch] (deathwatch-1.7.10-1.1.jar) 
	UCHIJAAAA	dmod{1.0.3.5} [D-Mod] (DMod-1.7.10-1.0.3.5.jar) 
	UCHIJAAAA	dsurround{1.0.6.4} [Dynamic Surroundings] (DynamicSurroundings-1.7.10-1.0.6.4.jar) 
	UCHIJAAAA	MineTweaker3{3.0.10} [MineTweaker 3] (MineTweaker3-1.7.10-3.0.10B.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	TwilightForest{2.3.8dev} [The Twilight Forest] (twilightforest-1.7.10-2.3.8.jar) 
	UCHIJAAAA	etfuturum{2.5.0} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.5.0.jar) 
	UCHIJAAAA	GraveStone{2.16.1} [GraveStone] (GraveStone_1.7.10_2.16.1.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	jaff{1.4.2_for_1.7.10} [Just a Few Fish] (JustAFewFish-1.4.2_for_1.7.10.jar) 
	UCHIJAAAA	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCHIJAAAA	MobProperties{1.0.2} [Mob Properties] (MobProperties-1.7.10-1.0.2.jar) 
	UCHIJAAAA	modtweaker2{0.9.6} [Mod Tweaker 2] (ModTweaker2-0.9.6.jar) 
	UCHIJAAAA	mowziesmobs{1.2.9} [Mowzie's Mobs] (MowziesMobs-1.2.99.jar) 
	UCHIJAAAA	mycroordinatesmods{1.0} [My Coordinates Mod] (My+Coordinates+Mods-1.7.10-0.1.jar) 
	UCHIJAAAA	netherlicious{3.2.8} [§6Netherlicious] (netherlicious-3.2.8.jar) 
	UCHIJAAAA	notenoughpets{2.3.4} [§eNot Enough Pets] (NotEnoughPets-1.7.10-2.3.4.jar) 
	UCHIJAAAA	primitivemobs{1.0} [Primitive Mobs] (primitivemobs-1.0c-1.7.10.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	RedstonePasteMod{1.6.2} [Redstone Paste] (RedstonePasteMod-1.7.10-1.6.2.jar) 
	UCHIJAAAA	thebetweenlands{1.0.7} [The Betweenlands] (TheBetweenlands-1.0.7-universal.jar) 
	UCHIJAAAA	erebus{0.4.7} [Erebus] (TheErebus-0.4.7.jar) 
	UCHIJAAAA	VillageNames{4.4.4} [§6Village Names] (VillageNames-1.7.10-4.4.4.jar) 
	UCHIJAAAA	witchery{0.24.1} [Witchery] (witchery-1.7.10-0.24.1.jar) 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 1 / 8; [EntityPlayerMP['Lotar II'/1187, l='ДэдВуд', x=618,00, y=93,00, z=1214,20]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.7.10_HD_U_E7
	Render Distance Chunks: 14
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 537.34
	OpenGlRenderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by Roadhog360** [comment]
Can you please use paste bin or other forms of text websites for crash reports

**Comment by GregoriusT** [comment]
first of all github has gist for pastes built in, secondly, the crash report contains everything you need in the post, which makes it way more convenient, so no need to ask for more. ;)

**Comment by Roadhog360** [comment]
I think it's good practice to ask for it anyways so future reports from the user don't involve scrolling through a massive wall of disorganized text which might be hit with random formatting due to underscores in the report or something.
