### ISSUE TITLE
Incompatible with module gadomancy 1.1.3

### ISSUE THREAD

**Issue by ABKQPO** [Roadhog360/Et-Futurum-Requiem#415]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.3.0+

### Describe the Issue

When I started the game, the loading progress got stuck at 66%, and then the game crashed with an error displayed

```
java.lang.NullPointerException: Cannot invoke "net.minecraft.enchantment.Enchantment.func_77321_a(int)" because "input" is null
	at thaumcraft.api.crafting.InfusionEnchantmentRecipe.<init>(InfusionEnchantmentRecipe.java:33)
	at thaumcraft.api.ThaumcraftApi.addInfusionEnchantmentRecipe(ThaumcraftApi.java:220)
	at makeo.gadomancy.common.registration.RegisteredRecipes.init(RegisteredRecipes.java:743)
	at makeo.gadomancy.common.CommonProxy.initalize(CommonProxy.java:74)
	at makeo.gadomancy.common.Gadomancy.init(Gadomancy.java:79)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.initializeMods(Loader.java:737)
	at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:319)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:210)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

But when I used module versions below 2.2.0, Botania encountered an exception

```
java.lang.RuntimeException: Enum ganymedes01.etfuturum.tileentities.TileEntityBanner$EnumBannerPattern was not made extensible, add it to lwjgl3ify configs.
	at net.minecraftforge.common.util.EnumHelper.addEnum(EnumHelper.java:134)
	at vazkii.botania.common.integration.etfuturum.ModBanners.addPattern(ModBanners.java:49)
	at vazkii.botania.common.integration.etfuturum.ModBanners.init(ModBanners.java:24)
	at vazkii.botania.common.core.proxy.CommonProxy.preInit(CommonProxy.java:123)
	at vazkii.botania.common.Botania.preInit(Botania.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
	at jdk.internal.reflect.GeneratedMethodAccessor7.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
	at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
	at cpw.mods.fml.common.Loader.preinitializeMods(Loader.java:556)
	at cpw.mods.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:88)
	at cpw.mods.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:314)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:117)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:387)
	at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685)
```

### Conflicting Mods

UCE	Botania{1.9.24-GTNH} [Botania] (Botania-1.9.24-GTNH.jar) 
UCE	botanichorizons{1.0.15-GTNH} [botanichorizons] (BotanicHorizons-1.0.15-GTNH.jar) 
UCHE	gadomancy{1.1.3} [Gadomancy] (gadomancy-1.1.3.jar) 

### Crash Report

https://rentry.co/ww3htgh7    https://rentry.co/xngfuaba

**Comment by SilearFlare** [comment]
That is incorrect. 
I am using gadomancy 1.13 and Et_Futurum_Requiem-2.6.0-SNAPSHOT-6c87e34 and my game has been running just fine.

`java.lang.RuntimeException: Enum ganymedes01.etfuturum.tileentities.TileEntityBanner$EnumBannerPattern was not made extensible, add it to lwjgl3ify configs.` And that one is clearly a lwj3 incompatibility, which you didn't even enumerate as a mod conflict (it conflicts with a great deal of mods outside of gtnh)
I'd suggest just renaming the issue altogether and finding the source of the issue.

**Comment by makamys** [comment]
LWJGL3ify compat was added in 2.4.4 so it makes sense earlier versions would crash with it.

No idea about the enchantment error, my guess would be you've got some misconfigured enchantment IDs.

**Comment by Roadhog360** [comment]
I don't get it. Does this issue happen with 2.5.1?

**Comment by herobrinein** [comment]
Strangely, I still encounter the issue of enchanting IDs when starting without using LWJGL3ify, and the version I am using is a 2.6.0 snapshot.
I'll try modifying the enchantment limit again
