### ISSUE TITLE
Broken Ore Dict entries

### ISSUE THREAD

**Issue by syndicate25** [Roadhog360/Et-Futurum-Requiem#463]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

2.6.0-rc-1

### Describe the Issue

It's nothing game breaking, but figured it could be easy to fix if it needed to be.  Found this while scrolling through the log during loading:

[22:05:43] [Client thread/WARN] [FML]: ****************************************
[22:05:43] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorWood has occurred. It adds an item (type: class net.malisis.doors.door.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod §5§oEt Futurum Requiem report it to them!
[22:05:43] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(Unknown Source)
[22:05:43] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(Unknown Source)
[22:05:43] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.recipes.ModRecipes.registerOreDictionary(ModRecipes.java:157)
[22:05:43] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.recipes.ModRecipes.init(ModRecipes.java:76)
[22:05:43] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.EtFuturum.postInit(EtFuturum.java:359)
[22:05:43] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:43] [Client thread/WARN] [FML]: ****************************************
[22:05:43] [Client thread/WARN] [FML]: ****************************************
[22:05:43] [Client thread/WARN] [FML]: * A broken ore dictionary registration with name doorIron has occurred. It adds an item (type: class net.malisis.doors.door.item.DoorItem) which is currently unknown to the game registry. This dictionary item can only support a single value when registered with ores like this, and NO I am not going to turn this spam off. Just register your ore dictionary entries after the GameRegistry.
TO USERS: YES this is a BUG in the mod §5§oEt Futurum Requiem report it to them!
[22:05:43] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOreImpl(Unknown Source)
[22:05:43] [Client thread/WARN] [FML]: *  at net.minecraftforge.oredict.OreDictionary.registerOre(Unknown Source)
[22:05:43] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.recipes.ModRecipes.registerOreDictionary(ModRecipes.java:164)
[22:05:43] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.recipes.ModRecipes.init(ModRecipes.java:76)
[22:05:43] [Client thread/WARN] [FML]: *  at ganymedes01.etfuturum.EtFuturum.postInit(EtFuturum.java:359)
[22:05:43] [Client thread/WARN] [FML]: *  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)...
[22:05:43] [Client thread/WARN] [FML]: ****************************************

### Conflicting Mods

NA

### Other Details

I can provide an entire log if you want, but I didn't feel that was necessary given it looks like just a couple entries need to be corrected.  Let me know and I can get you a full log if you want it.

**Comment by syndicate25** [comment]
This was reported a while back and I didn't clear the "open" flag when searching prior.  Disregard.

**Comment by Roadhog360** [comment]
That's weird, are you sure it's the same issue? Either way I'm tempted to say this is not my fault because EFR does not add other mod doors to the `doorWood` tag

**Comment by syndicate25** [comment]
Yeah they look identical to me. I just screwed up when searching for prior issues.  You said the same thing last time and there was a discussion about it with a few others that seemed to come to the same conclusion.  It's not hurting anything as far as I can tell anyway. 

I thought it was going to be a simple correction and I think it ended up being determined to be "MalisisDoors" that was doing it.  Only thing that mod does differently (that I'm aware of) is animate the doors opening and closing.  If you're doing that in EFR, then I can just get rid of MalisisDoors.

**Comment by GregoriusT** [comment]
What the heck is Malisis Doors doing?! Are they seriously replacing Vanilla Doors blindly and registering them to the OreDict inside the constructor assuming its already registered?!
