### ISSUE TITLE
thinPanes is not compatible with Angelica? (Error in using reflection method) 

### ISSUE THREAD

**Issue by Natsukiw** [Roadhog360/Et-Futurum-Requiem#485]
### Initial Questions

- [X] I have searched this issue tracker and there is nothing similar already, and this is not on the [list of known issues](https://github.com/Roadhog360/Et-Futurum-Requiem/issues/146). Posting on a closed issue saying the bug still exists will prompt us to investigate and reopen it once we confirm your report.
- [X] I have verified that this issue occurs in a SUPPORTED environment, meaning I can reproduce this WITHOUT OptiFine, and without Bukkit+Forge server software like KCauldron, Thermos, Crucible, Mohist etc

### Mod Version

last build 2024-7-1

### Describe the Issue

This error occurs when I turn off the mcpatcher function that comes with Angelica.
I think we can add a function to determine whether Angelica has the mcpatcher function turned on to avoid this error

Because the mcpatcher function that comes with Angelica is not perfect, I need to turn it off

`
[15:36:55] [Chunk Render Task Executor #1/ERROR]: MCPF compat failed to set up for stained glass panes. Pretending it's off for now (rendering may look wonky!)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: java.lang.NoSuchMethodException: com.prupe.mcpatcher.ctm.GlassPaneRenderer.setupPaneEdges(net.minecraft.client.renderer.RenderBlocks, net.minecraft.block.Block, int, int, int)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Class.getDeclaredMethod(Class.java:2130)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.RenderBlocks.loadReflectionData(RenderBlocks.java:11075)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.RenderBlocks.handler$zfd000$etfuturum$tweakStainedPaneRenderer(RenderBlocks.java:11013)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.RenderBlocks.func_147733_k(RenderBlocks.java:2734)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at net.minecraft.client.renderer.RenderBlocks.func_147805_b(RenderBlocks.java:286)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.jellysquid.mods.sodium.client.render.pipeline.BlockRenderer.renderModel(BlockRenderer.java:95)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.jellysquid.mods.sodium.client.render.chunk.tasks.ChunkRenderRebuildTask.performBuild(ChunkRenderRebuildTask.java:161)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:409)
[15:36:55] [Chunk Render Task Executor #1/INFO]: [java.lang.Throwable$WrappedPrintStream:println:749]: 	at java.lang.Thread.run(Thread.java:748)`

**Comment by Roadhog360** [comment]
Angelica might change the path of the utilities I reflect into, causing the error.

**Comment by Roadhog360** [comment]
They should preserve the signatures and paths of the mods they are inheriting. I will make compat for their version but please open an issue on their tracker, this is on their end.
