### ISSUE TITLE
client crashes when placing last eye of ender in the end portal

### ISSUE THREAD

**Issue by bambam01** [Roadhog360/Et-Futurum-Requiem#82]
When people are playing on a server and someone tries to put in the last eye of ender in a portal it crashes the client of the person putting in the eye. I think this happens because the mod tries to get the world servers that don't exists on the client. I think there should be a check to see if it is the client or the server

https://github.com/Roadhog360/Et-Futurum-Requiem/blob/df42b2a0dab0fc4b7aa5d3c527c9a46cd16329e6/src/main/java/ganymedes01/etfuturum/core/handlers/ServerEventHandler.java#L563-L577

this is the acctual crash:
```
[10:37:57] [Client thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.entity.player.PlayerInteractEvent@1c67b516:
java.lang.NullPointerException
	at ganymedes01.etfuturum.core.handlers.ServerEventHandler.onPlayerInteract(ServerEventHandler.java:565) ~[ServerEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler_7_ServerEventHandler_onPlayerInteract_PlayerInteractEvent.invoke(.dynamic) ~[?:?]
	at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
	at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:140) [EventBus.class:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerInteract(ForgeEventFactory.java:100) [ForgeEventFactory.class:?]
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1446) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1953) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_301]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_301]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_301]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by Roadhog360** [comment]
Strange that happens, since somehow it worked during my testing, as I had to test it being omnipresent between all players. I did tweak that code a little more after so I probably broke it then, thanks for the report.

A simple !worldObj.isRemote fixed it, this fix will be added to the upcoming release of Et Futurum.

**Comment by Roadhog360** [comment]
Should be fixed in the latest download.
