### ISSUE TITLE
Waxing, unwaxing or scraping copper blocks crashes the server

### ISSUE THREAD

**Issue by KAMKEEL** [Roadhog360/Et-Futurum-Requiem#87]
A problem when scraping Wax off of Copper. 

```---- Minecraft Crash Report ----
// But it works on my machine.

Time: 11/8/21 5:22 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: ganymedes01/etfuturum/client/particle/ParticleHandler
	at ganymedes01.etfuturum.blocks.IDegradable.spawnParticles(IDegradable.java:222)
	at ganymedes01.etfuturum.blocks.IDegradable.tryWaxOnWaxOff(IDegradable.java:155)
	at ganymedes01.etfuturum.blocks.BlockCopper.func_149727_a(BlockCopper.java:51)
	at net.minecraft.server.management.ItemInWorldManager.func_73078_a(ItemInWorldManager.java:465)
	at net.minecraft.network.NetHandlerPlayServer.func_147346_a(NetHandlerPlayServer.java:862)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:60)
	at net.minecraft.network.play.client.C08PacketPlayerBlockPlacement.func_148833_a(SourceFile:9)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:245)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:181)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:1023)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:431)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:842)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:692)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: ganymedes01.etfuturum.client.particle.ParticleHandler
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 14 more
Caused by: java.lang.RuntimeException: Attempted to load class ganymedes01/etfuturum/client/particle/ParticleHandler for invalid side SERVER
	at cpw.mods.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:51)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 16 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Thermos Version: cruciblemc:Crucible:1.7.10-4.1
	Plugins: AutoSaveWorld, LuckPerms, AsyncWorldEdit, ArcaneEnchants, MazeGenerator, RepairAll, Essentials, VoxelSniper, EssentialsChat, DeathMessages, PluginHealth, Vault, RPGMessenger, EssentialsSpawn, MyCommand, Multiverse-Core, WorldEdit, Coinage, ChestCommands, WorldGuard, WeatherMan, Crucible_Server
	Disabled Plugins: 
	Operating System: Linux (amd64) version 4.19.0-16-amd64
	Java Version: 1.8.0_312, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4805965712 bytes (4583 MB) / 8344567808 bytes (7958 MB) up to 8344567808 bytes (7958 MB)
	JVM Flags: 4 total; -XX:+UseContainerSupport -Xms8000M -Xmx8000M -Xverify:none
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 17, tcache: 0, allocated: 12, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 167 mods loaded, 157 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	Crucible{4.1} [Crucible Server] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (crucible.jar) 
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (crucible.jar) 
	UCHIJAAAA	kimagine{0.2} [KImagine] (minecraft.jar) 
	UCHIJAAAA	AppleMilkCore{1.1.0} [AppleMilkCore] (minecraft.jar) 
	UCHIJAAAA	appliedenergistics2-core{rv3-beta-6} [Applied Energistics 2 Core] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.7.48} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	se{0.4.1} [Super Enchants] (minecraft.jar) 
	UCHIJAAAA	ivtoolkit{1.2.1} [IvToolkit] (minecraft.jar) 
	UCHIJAAAA	Micdoodlecore{} [Micdoodle8 Core] (minecraft.jar) 
	UCHIJAAAA	MobiusCore{1.2.5} [MobiusCore] (minecraft.jar) 
	UCHIJAAAA	PotionExtensionCore{1.7.10-1.1.0} [PotionExtensionCore] (minecraft.jar) 
	UCHIJAAAA	OpenModsCore{0.10.1} [OpenModsCore] (minecraft.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	mod_ThreadedLighting{1.7.10-1.0} [Threaded Lighting] (minecraft.jar) 
	UCHIJAAAA	psychedelicraftcore{1.4} [Psychedelicraft Core] (minecraft.jar) 
	UCHIJAAAA	ExtendedPotions{1.2} [Extended Potions] (ExtendedPotions-MC1.7.10-1.2.jar) 
	UCHIJAAAA	gilded-games-util{1.7.10-1.2} [Gilded Games Utility] (gilded-games-util-1.7.10-1.10.jar) 
	UCHIJAAAA	Mantle{1.7.10-0.3.2.jenkins191} [Mantle] (Mantle-1.7.10-0.3.2b.jar) 
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	ThermalFoundation{1.7.10R1.2.6} [Thermal Foundation] (ThermalFoundation-[1.7.10]1.2.6-118.jar) 
	UCHIJAAAA	ForgeMultipart{1.2.0.345} [Forge Multipart] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.12} [Extra Utilities] (extrautilities-1.2.12.jar) 
	UCHIJAAAA	MineFactoryReloaded{1.7.10R2.8.1} [MineFactory Reloaded] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	ThermalExpansion{1.7.10R4.1.5} [Thermal Expansion] (ThermalExpansion-[1.7.10]4.1.5-248.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	TConstruct{1.7.10-1.8.8.build988} [Tinkers' Construct] (TConstruct-1.7.10-1.8.8.jar) 
	UCHIJAAAA	GalacticraftCore{3.0.12} [Galacticraft Core] (GalacticraftCore-1.7-3.0.12.504.jar) 
	UCHIJAAAA	SpaceCore{4.1.9} [4Space Core] (4Space-4.1.9.jar) 
	UCHIJAAAA	ExoCore{0.1.2} [4Space Exoplanets Core] (4Space-4.1.9.jar) 
	UCHIJAAAA	ExoElipse{0.1.2} [4Space Exoplanets Elipse] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceCallisto{4.1.9} [4Space Callisto] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceEuropa{4.1.9} [4Space Europa] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceVenus{4.1.9} [4Space Venus] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceIo{4.1.9} [4Space Io] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpaceMercury{4.1.9} [4Space Mercury] (4Space-4.1.9.jar) 
	UCHIJAAAA	SpacePluto{4.1.9} [4Space Pluto] (4Space-4.1.9.jar) 
	UCHIJAAAA	cheesemod{4.3} [�6Cheese Mod] ([1.7.10]+Cheese+Mod+v+4.3.jar) 
	UCHIJAAAA	FLabsBF{4.3} [Better Furnaces] ([1.7.10]Better_Furnaces_V4.3.jar) 
	UCHIJAAAA	abyssalcraft{1.9.1.3} [AbyssalCraft] (AbyssalCraft-1.7.10-1.9.1.3-FINAL.jar) 
	UCHIJAAAA	advancedcapes{1.5} [Advanced Capes] (advancedcapes-1.5.jar) 
	UCHIJAAAA	aether{1.7.10-1.6} [Aether II] (Aether2.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	AppleCore{1.3.9} [AppleCore] (AppleCore-mc1.7.10-1.3.9.jar) 
	UCHIJAAAA	DCsAppleMilk{1.7.10_2.9n} [Apple&Milk&Tea!] (AppleMilkTea2-1.7.10_2.9n.jar) 
	UCHIJAAAA	DCsNEIPluginAMT{1.7.10_1.0a} [NEIPluginForAMT] (AppleMilkTea2-1.7.10_2.9n.jar) 
	UCHIJAAAA	appliedenergistics2{rv3-beta-6} [Applied Energistics 2] (appliedenergistics2-rv3-beta-6.jar) 
	UCHIJAAAA	Aquaculture{1.2.6} [Aquaculture] (Aquaculture-1.7.10-1.2.6.21.jar) 
	UCHIJAAAA	mod_AsyncWorldEdit_Injector{2.1.0} [AsyncWorldEdit Injector] (AsyncWorldEditInjector.jar) 
	UCHIJAAAA	bis{3.1.6} [Back in Slime Mod] (Back In Slime-1.7.10-3.1.6.jar) 
	UCHIJAAAA	Backpack{2.0.1} [Backpack] (backpack-2.0.1-1.7.x.jar) 
	UCHIJAAAA	BiblioCraft{1.11.6} [BiblioCraft] (BiblioCraft[v1.11.6][MC1.7.10].jar) 
	UCHIJAAAA	Natura{2.2.0} [Natura] (natura-1.7.10-2.2.1a2.jar) 
	UCHIJAAAA	BiomesOPlenty{2.1.0} [Biomes O' Plenty] (BiomesOPlenty-1.7.10-2.1.0.2308-universal.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Botania{r1.8-249} [Botania] (Botania+r1.8-249.jar) 
	UCHIJAAAA	campfirebackport{1.7.10-1.9.2} [Campfire Backport] (campfirebackport-1.7.10-1.9.2.jar) 
	UCHIJAAAA	TwilightForest{2.3.8dev} [The Twilight Forest] (twilightforest-1.7.10-2.3.8.jar) 
	UCHIJAAAA	chisel{2.9.5.11} [Chisel] (Chisel-2.9.5.11.jar) 
	UCHIJAAAA	colorblocksplus{1.0} [Color Blocks Plus] (Color+Blocks+Plus+-+1.0.jar) 
	UCHIJAAAA	CoroAI{v1.0} [CoroAI] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	BuildMod{v1.0} [Build Mod] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	CoroPets{v1.0} [CoroPets] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ExtendedRenderer{v1.0} [Extended Renderer] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	ConfigMod{v1.0} [Extended Mod Config] (coroutil-1.7.10-1.1.6.jar) 
	UCHIJAAAA	cosmeticarmorreworked{1.7.10-v6b} [CosmeticArmorReworked] (CosmeticArmorReworked-1.7.10-v6b.jar) 
	UCHIJAAAA	CraftHeraldry{1.1.3} [CraftHeraldry] (CraftHeraldry+1.1.3.jar) 
	UCHIJAAAA	craftingpillars{1.6.0} [Crafting Pillars Mod] (CraftingPillars-1.7.x-1.6.1.jar) 
	UCHIJAAAA	creativecore{1.3.14} [CreativeCore] (CreativeCore+v1.3.24+mc1.7.10.jar) 
	UCHIJAAAA	CustomSpawner{3.3.0} [DrZhark's CustomSpawner] (CustomMobSpawner+3.3.0.zip) 
	UCHIJAAAA	customnpcs{1.2.3} [CustomNpcs] (CustomNPC-Plus-1.23.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.7.10.jar) 
	UCHIJAAAA	doorsoplenty{0.1} [Doors o Plenty] (doorsoplenty-1.0.jar) 
	UCHIJAAAA	MoCreatures{6.3.1} [DrZhark's Mo'Creatures Mod] (DrZharks MoCreatures Mod v6.3.1.zip) 
	UCHIJAAAA	endercore{1.7.10-0.2.0.36_beta} [EnderCore] (EnderCore-1.7.10-0.2.0.36_beta.jar) 
	UCHIJAAAA	EnderIO{1.7.10-2.3.0.429_beta} [Ender IO] (EnderIO-1.7.10-2.3.0.429_beta.jar) 
	UCHIJAAAA	etfuturum{2.3.0-beta-2} [§5§oEt Futurum Requiem] (Et_Futurum_Requiem-2.3.0-beta-2.jar) 
	UCHIJAAAA	eternalfrost{2.0b4} [Eternal Frost] (eternalfrost-2.0b6.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10Lb.jar) 
	UCHIJAAAA	ExtraTiC{1.4.6} [ExtraTiC] (ExtraTiC-1.7.10-1.4.6.jar) 
	UCHIJAAAA	fc-dummy{0} [fc-dummy] (fastcraft-1.25.jar) 
	UCHIJAAAA	FlatSigns{2.1.0.19} [Flat Signs] (FlatSigns-1.7.10-universal-2.1.0.19.jar) 
	UCHIJAAAA	llibrary{1.5.1} [LLibrary] (llibrary-1.5.1-1.7.10.jar) 
	UCHIJAAAA	fossil{7.3.2} [Fossils and Archeology Revival] (fossilsarcheology-7.3.2.jar) 
	UCHIJAAAA	GalacticraftMars{3.0.12} [Galacticraft Planets] (Galacticraft-Planets-1.7-3.0.12.504.jar) 
	UCHIJAAAA	GardenContainers{1.7.10-1.7.0} [Garden Containers] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenCore{1.7.10-1.7.0} [Garden Core] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenStuff{1.7.10-1.7.0} [Garden Stuff] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	GardenTrees{1.7.10-1.7.0} [Garden Trees] (GardenStuff-1.7.10-1.7.0.jar) 
	UCHIJAAAA	grapplemod{1.7.10-v10} [Grappling hook mod] (grapplemod-1.7.10-v10.jar) 
	UCHIJAAAA	iChunUtil{4.2.3} [iChunUtil] (iChunUtil-4.2.3.jar) 
	UCHIJAAAA	Hats{4.0.1} [Hats] (Hats-4.0.1.jar) 
	UCHIJAAAA	HealthBar{1.0.2} [Health Bar] (HealthBar-1.7.10-1.0.2-11.jar) 
	UCHIJAAAA	HexWool{0.4.2.16} [HexWool] (HexWool-1.7.10-0.4.2.16.jar) 
	UCHIJAAAA	inpure|core{1.7.10R1.0.0B9} [INpureCore] (INpureCore-[1.7.10]1.0.0B9-62.jar) 
	UCHIJAAAA	ironbackpacks{1.7.10-1.2.20} [Iron Backpacks] (IronBackpacks-1.7.10-1.2.20.jar) 
	UCHIJAAAA	IronChest{6.0.62.742} [Iron Chest] (ironchest-1.7.10-6.0.62.742-universal.jar) 
	UCHIJAAAA	journeymap{5.1.4p2} [JourneyMap] (journeymap-1.7.10-5.1.4p2-unlimited.jar) 
	UCHIJAAAA	locks{1.0.0} [Locks] (Locks-1.0.0.jar) 
	UCHIJAAAA	mam{1.7.10-1.0.2} [Myths & Monsters Mod] (mam-1.7.10-1.0.2.jar) 
	UCHIJAAAA	RadixCore{2.1.3} [RadixCore] (RadixCore-1.7.10-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.7.10-5.2.2} [Minecraft Comes Alive] (MCA-1.7.10-5.2.2-universal.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatAppliedEnergistics{1.7.10R2.8.1} [MFR Compat: Applied Energistics] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatForgeMicroblock{1.7.10R2.8.1} [MFR Compat: ForgeMicroblock] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThaumcraft{1.7.10R2.8.1} [MFR Compat: Thaumcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatThermalExpansion{1.7.10R2.8.1} [MFR Compat: Thermal Expansion] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTConstruct{1.7.10R2.8.1} [MFR Compat: Tinkers' Construct] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatTwilightForest{1.7.10R2.8.1} [MFR Compat: TwilightForest] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	MineFactoryReloaded|CompatVanilla{1.7.10R2.8.1} [MFR Compat: Vanilla] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UCHIJAAAA	Mo' Shiz{1.62.2} [Mo' Shiz] (Mo'+Shiz+v1.62.2.jar) 
	UCHIJAAAA	MoreDyes{1.7.10-1.0.8} [More Dyes] (moredyes-1.7.10-1.0.8.jar) 
	UCHIJAAAA	moreplayermodels{1.7.10b} [MorePlayerModels] (MorePlayerModels_1.7.10.jar) 
	UCHIJAAAA	mowziesmobs{1.2.9} [Mowzie's Mobs] (MowziesMobs-1.2.99.jar) 
	UCHIJAAAA	cfm{3.4.7} [�9MrCrayfish's Furniture Mod] (MrCrayfishFurnitureModv3.4.7(1.7.10).jar) 
	UCHIJAAAA	MutantCreatures{1.4.9} [Mutant Creatures] (MutantCreatures-1.7.10-1.4.9.jar) 
	UCHIJAAAA	yumalib{0.0.0} [YumaLib] (UpToDateMod-mc1.7.10-2.3.11.jar) 
	UCHIJAAAA	uptodate{2.3.10} [UpToDateMod] (UpToDateMod-mc1.7.10-2.3.11.jar) 
	UCHIJAAAA	netherlicious{3.0.7} [§6Netherlicious] (netherlicious-3.0.7.jar) 
	UCHIJAAAA	nhlib{2.0.11} [NHAVE's Library] (nhlib-1.7.10-2.0.11.jar) 
	UCHIJAAAA	nhtech{1.0.7} [NHAVE's Tech Mod] (nhtech-1.7.10-1.0.7.jar) 
	UCHIJAAAA	recipehandler{1.7.10} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.3(1.7.10).jar) 
	UCHIJAAAA	notenoughIDs{1.4.3.4} [NotEnoughIDs] (NotEnoughIDs-1.4.3.4.jar) 
	UCHIJAAAA	opframe{0.1} [OnlinePictureFrame] (OnlinePicFrame+v1.0+mc1.7.10.jar) 
	UCHIJAAAA	OpenMods{0.10.1} [OpenMods] (OpenModsLib-1.7.10-0.10.1.jar) 
	UCHIJAAAA	OpenBlocks{1.6} [OpenBlocks] (OpenBlocks-1.7.10-1.6.jar) 
	UCHIJAAAA	MapWriter{2.1.2} [MapWriter] (Opis.jar) 
	UCHIJAAAA	Opis{1.2.5} [Opis] (Opis.jar) 
	UCHIJAAAA	plug{4.2} [The Plugin Mod] (PluginMod-4.2.jar) 
	UCHIJAAAA	potioncore{@VERSION@} [Potion Core] (PotionCore.jar) 
	UCHIJAAAA	MrTJPCoreMod{1.1.0.33} [MrTJPCore] (MrTJPCore-1.1.0.33-universal.jar) 
	UCHIJAAAA	ProjRed|Core{4.7.0pre12.95} [ProjectRed Core] (ProjectRed-1.7.10-4.7.0pre12.95-Base.jar) 
	UCHIJAAAA	ProjRed|Integration{4.7.0pre12.95} [ProjectRed Integration] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	ProjRed|Transmission{4.7.0pre12.95} [ProjectRed Transmission] (ProjectRed-1.7.10-4.7.0pre12.95-Integration.jar) 
	UCHIJAAAA	psychedelicraft{1.5.2} [Psychedelicraft] (Psychedelicraft-1.5.2.jar) 
	UCHIJAAAA	RedstoneArsenal{1.7.10R1.1.2} [Redstone Arsenal] (RedstoneArsenal-[1.7.10]1.1.2-92.jar) 
	UCHIJAAAA	ropebridge{1.3} [Rope Bridge] (RopeBridge-v1.3-mc1.7.10.jar) 
	UCHIJAAAA	SilentGems{1.3.14} [Silent's Gems] (SilentGems-1.7.10-1.3.14-172.jar) 
	UCHIJAAAA	simplecore{1.1.1.3} [SimpleCore API] (simplecore-1.7.10-1.1.1.3.jar) 
	UCHIJAAAA	simpleores{1.6.1.4} [SimpleOres 2] (simpleores-1.7.10-1.6.1.4.jar) 
	UCHIJAAAA	simplyjetpacks{1.5.3} [Simply Jetpacks] (SimplyJetpacks-MC1.7.10-1.5.3.jar) 
	UCHIJAAAA	SkyForge{Version 1.0 > 1.7.10} [SkyForge Mod] (SkyForge-Beta 2.2.2.jar) 
	UCHIJAAAA	SolarFlux{1.7.10-0.8b} [Solar Flux] (SolarFlux-1.7.10-0.8b.jar) 
	UCHIJAAAA	SpiceOfLife{1.3.11} [The Spice of Life] (SpiceOfLife-mc1.7.10-1.3.11.jar) 
	UCHIJAAAA	elysium{1.0} [The Elysium] (TheElysium-1.7.x-1.0.3.jar) 
	UCHIJAAAA	kitchen{1.3.23} [The Kitchen Mod] (TheKitchenMod-1.3.23-1.7.2-10.jar) 
	UCHIJAAAA	WallpaperCraft{1.7.10} [WallpaperCraft] (WallpaperCraft-1.7.10-1.03.jar) 
	UCHIJAAAA	wanionlib{1.7.10-1.8} [WanionLib] (WanionLib-1.7.10-1.8.jar) 
	UCHIJAAAA	weaponmod{v1.14.3} [Balkon's WeaponMod] (weaponmod-1.14.3.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (worldedit-forge-mc1.7.10-6.1.1-dist.jar) 
	UCHIJAAAA	ZoocraftDiscoveries{1.0} [Zoocraft Discoveries] (Zoocraft+Discoveries+1.7.10-1.1.0.jar) 
	UCHIJAAAA	Ztones{1.7.10} [Ztones] (Ztones-1.7.10-2.2.1.jar) 
	UCHIJAAAA	McMultipart{1.2.0.345} [Minecraft Multipart Plugin] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UCHIJAAAA	UniDict{1.7.10-2.9.2} [UniDict] (UniDict-1.7.10-2.9.2.jar) 
	UCHIJAAAA	ForgeMicroblock{1.2.0.345} [Forge Microblocks] (ForgeMultipart-1.7.10-1.2.0.345-universal.jar) 
	UD	MineFactoryReloaded|CompatAtum{1.7.10R2.8.1} [MFR Compat: Atum] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBackTools{1.7.10R2.8.1} [MFR Compat: BackTools] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatBuildCraft{1.7.10R2.8.1} [MFR Compat: BuildCraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatChococraft{1.7.10R2.8.1} [MFR Compat: Chococraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatExtraBiomes{1.7.10R2.8.1} [MFR Compat: ExtraBiomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatForestry{1.7.10R2.8.1} [MFR Compat: Forestry] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatIC2{1.7.10R2.8.1} [MFR Compat: IC2] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatProjRed{1.7.10R2.8.1} [MFR Compat ProjectRed] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatRailcraft{1.7.10R2.8.1} [MFR Compat: Railcraft] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	UD	MineFactoryReloaded|CompatSufficientBiomes{1.7.10R2.8.1} [MFR Compat: Sufficient Biomes] (MineFactoryReloaded-[1.7.10]2.8.1-174.jar) 
	OpenModsLib class transformers: [stencil_patches:ENABLED],[movement_callback:ENABLED],[player_damage_hook:ACTIVATED],[map_gen_fix:FINISHED],[gl_capabilities_hook:ENABLED],[player_render_hook:ENABLED]
	Class transformer null safety: all safe
	Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: bukkit
	CoFHCore: -[1.7.10]3.1.4-329
	ThermalFoundation: -[1.7.10]1.2.6-118
	MineFactoryReloaded: -[1.7.10]2.8.1-174
	ThermalExpansion: -[1.7.10]4.1.5-248
	TConstruct Environment: Environment healthy.
	AE2 Version: beta rv3-beta-6 for Forge 10.13.4.1448
	RedstoneArsenal: -[1.7.10]1.1.2-92
	Chisel: Errors like "[FML]: Unable to lookup ..." are NOT the cause of this crash. You can safely ignore these errors. And update forge while you're at it.
	EnderIO: Found the following problem(s) with your installation:
                  * An unknown AE2 API is installed (rv3 from appliedenergistics2-rv3-beta-6.jar).
                    Ender IO was build against API version rv2 and may or may not work with a newer version.
                 An unsupported base software is installed: 'thermos, cauldron, craftbukkit, mcpc, kcauldron'. This is NOT supported.
                 This may have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
	AE2 Integration: IC2:OFF, RotaryCraft:OFF, RC:OFF, BuildCraftCore:OFF, BuildCraftTransport:OFF, BuildCraftBuilder:OFF, RF:ON, RFItem:ON, MFR:ON, DSU:ON, FZ:OFF, FMP:ON, RB:OFF, CLApi:OFF, Waila:ON, Mekanism:OFF, ImmibisMicroblocks:OFF, BetterStorage:OFF, OpenComputers:OFF, PneumaticCraft:OFF
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Player Count: 2 / 6; [GCEntityPlayerMP['MDSMVP'/37268, l='world', x=864.17, y=65.00, z=1296.84](MDSMVP at 864.1729287296736,65.0,1296.8358115727397), GCEntityPlayerMP['Kam'/40861, l='world', x=866.47, y=65.00, z=1299.63](Kam at 866.470699679923,65.0,1299.6339866420242)]
	Is Modded: Definitely; Server brand changed to 'thermos,cauldron,craftbukkit,mcpc,kcauldron,fml,forge'
	Type: Dedicated Server (map_server.txt)```

**Comment by Roadhog360** [comment]
Ah yes, the classic case of "code that was working before suddenly decides you need to change it for it to work again"... A classic in Minecraft modding for me.

**Comment by KAMKEEL** [comment]
Yeah, I figured it was a quick fix. Hey, @Roadhog360 I wouldn't mind chipping in a bit on this project to backport some blocks for simple utility.

**Comment by Roadhog360** [comment]
Oh yes. That is fine by me. Feel free to make a pullr equest and when I get home I can show you how to properly use our interfaces properly when I get home. Join the support Discord linked on CurseForge to stay in touch!
